logger:
  level: "info"
storage: "memory"
db:
  dsn: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  migrations_dir: "./migrations/"
server:
  host: "localhost"
  port: 4242
  read_timeout: 1s
  write_timeout: 1s